### ISSUE TITLE
Export command as a library

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/wally-package-types#1]
We have an internal tool for hoisting package types, currently it is just using some basic regex that may break with edge cases, it would be great if we could replace that part of the tool with this!
This could be done in a similar way to Wally & Rojo, both export a lib that contains command structs with a `run` method on them, there's no need to get more granular for our particular use case.

**Comment by JohnnyMorganz** [comment]
Happy to accept a PR for this!
