### ISSUE TITLE
Generic defaults aren't re-exported

### ISSUE THREAD

**Issue by Hexcede** [JohnnyMorganz/wally-package-types#10]
Generic defaults like these aren't re-exported correctly:
```lua
export type Abc<A, B=A> = ...
```
Instead they are re-exported as:
```lua
export type Abc<A, B > = ...
```

This affects packages like Fusion, which has the type `export type Value<T, S=T>`.

There are some considerations to be made here, because a script could export a type that's privately defined inside the script file, so I can understand why this may not be something worth supporting.

**Comment by JohnnyMorganz** [comment]
Makes sense, happy to accept a PR for this. Indeed as you mention though, care needs to be taken when the default type is referencing other types within the module, particular if those other types are private (or, even harder, if they come from a different module altogether)

**Comment by JohnnyMorganz** [comment]
Prior reason why we didn't support this: #4.

I will put up a fix for now that will handle the case where the default is part of the type, which should solve the Fusion case.
