### ISSUE TITLE
Support for cross-realm package links

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/wally-package-types#3]
Wally supports two different kinds of package links:

- Relative - `require(script.Parent["..."]["..."])`
- Absolute - `require(game.Service.Path["..."]["..."])`

This tool currently only supports the former, and panics with the message `thread 'main' panicked at 'assertion failed: iter.next().unwrap() == \"script\"', src/command.rs:214:9` for the latter.
Support for absolute paths in links would be great 👍

**Comment by JohnnyMorganz** [comment]
Supported in https://github.com/JohnnyMorganz/wally-package-types/commit/1e292fc49cb690dfbcc131b40153f1ece7805ef2
