### ISSUE TITLE
Wally-package-types does not support string interpolation

### ISSUE THREAD

**Issue by Aloroid** [JohnnyMorganz/wally-package-types#5]
Currently when attempting to add types for a luau module that uses string interpolation, it produces the following error:
`thread 'main' panicked at 'unknown require expression', src\command.rs:110:18`

**Comment by JohnnyMorganz** [comment]
Do you have an example package which I can test on?

**Comment by Aloroid** [comment]
This package uses string interpolation
`ecr = "centau/ecr@0.4.0"`
